# GAP Themes

PACKAGE_NAME = GAPTHEMES
include $(GNUSTEP_MAKEFILES)/common.make

#
# We have no themes to install yet!  Once we have them, add them to
# the Themes_RESOURCE_FILES variable.
# 
RESOURCE_SET_NAME = Themes
Themes_INSTALL_DIR = $(GNUSTEP_LIBRARY)/Themes
Themes_RESOURCE_FILES = Neos.theme \
ThinkDark.theme \
Sleek.theme \
WinClassic.theme

include $(GNUSTEP_MAKEFILES)/resource-set.make
