.TH ZIPPER 1 "November 10, 2004"
.SH NAME
Zipper \- inspect and extract compressed archives
.SH SYNOPSIS
.B Zipper
.SH DESCRIPTION
This manual page documents briefly the
.B Zipper
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
\fBZipper\fP is a tool for inspecting the contents of a compressed archive
and for extracting.
.SH SEE ALSO
.BR GNUstep (7).
.SH AUTHOR
This manual page was written by G\[:u]rkan Myczko <gurkan@phys.ethz.ch>,
for the Debian project (but may be used by others).
