#
# GNUmakefile - Generated by ProjectCenter
#

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = DataBasin
APP_NAME = DataBasin
DataBasin_APPLICATION_ICON = 


#
# Libraries
#
DataBasin_LIBRARIES_DEPEND_UPON += -lWebServices 

#
# Resource files
#
DataBasin_RESOURCE_FILES = \
Resources/DataBasin.gorm \


#
# Header files
#
DataBasin_HEADER_FILES = \
AppController.h \
DBSoap.h

#
# Class files
#
DataBasin_OBJC_FILES = \
AppController.m \
DBSoap.m

#
# Other sources
#
DataBasin_OBJC_FILES += \
main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
