ADDITIONAL_OBJCFLAGS += -Wall -I../

ifeq ($(DOUBLE_RELEASE_COUNT), YES)
ADDITIONAL_OBJCFLAGS += -DDOUBLE_RELEASE_COUNT
endif

ifeq ($(OBJC_RUNTIME_LIB), apple)
ADDITIONAL_OBJCFLAGS += -I../Misc -include GNUstep.h $(ADDITIONAL_FRAMEWORK_DIRS)
ADDITIONAL_LDFLAGS +=  -F../TalkSoupBundles
else
ADDITIONAL_LDFLAGS += -L../TalkSoupBundles/TalkSoupBundles.framework/Versions/Current
endif

