#
# StepMan InnerSpace module
#

StepMan_PRINCIPAL_CLASS = StepManView

include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = StepMan
BUNDLE_EXTENSION = .InnerSpace

StepMan_OBJC_FILES = StepManView.m
StepMan_PRINCIPAL_CLASS = StepManView
StepMan_STANDARD_INSTALL = no
StepMan_RESOURCE_FILES = GNUstep.tiff

-include GNUmakefile.preamble

-include ../GNUmakefile.local

-include $(GNUSTEP_MAKEFILES)/bundle.make

-include GNUmakefile.postamble
