#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
  ifeq ($(GNUSTEP_MAKEFILES),)
    $(warning )
    $(warning Unable to obtain GNUSTEP_MAKEFILES setting from gnustep-config!)
    $(warning Perhaps gnustep-make is not properly installed,)
    $(warning so gnustep-config is not in your PATH.)
    $(warning )
    $(warning Your PATH is currently $(PATH))
    $(warning )
  endif
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.6
PACKAGE_NAME = Graphos
APP_NAME = Graphos
Graphos_APPLICATION_ICON = graphos_appicon_48.tif


#
# Resource files
#
Graphos_RESOURCE_FILES = \
Resources/GRDocument.gorm \
Resources/MainMenu.gorm \
Resources/PropertiesEditor.gorm \
Resources/bezier.tiff \
Resources/blackarrow.tiff \
Resources/hand.tiff \
Resources/LineCap1.tiff \
Resources/LineCap2.tiff \
Resources/LineCap3.tiff \
Resources/LineJoin1.tiff \
Resources/LineJoin2.tiff \
Resources/LineJoin3.tiff \
Resources/magnify.tiff \
Resources/paint.tiff \
Resources/pencil.tiff \
Resources/rectangle.tiff \
Resources/reduce.tiff \
Resources/reflect.tiff \
Resources/rotate.tiff \
Resources/shissors.tiff \
Resources/text.tiff \
Resources/txtAlignCenter.tiff \
Resources/txtAlignLeft.tiff \
Resources/txtAlignRight.tiff \
Resources/whitearrow.tiff \
Resources/x.tiff \
Resources/graphos_appicon_48.tif \
Resources/circle.tiff \
Resources/graphos_doc_icon_48.tif \
Resources/GraphosInfo.plist 


#
# Header files
#
Graphos_HEADER_FILES = \
Graphos.h \
GRBezierControlPoint.h \
GRBezierPathEditor.h \
GRDocument.h \
GRDocView.h \
GRFunctions.h \
GRPropsEditor.h \
GRText.h \
GRTextEditor.h \
GRTextEditorView.h \
GRTools.h \
GRBox.h \
GRBoxEditor.h \
GRBezierPath.h \
GRObjectEditor.h \
GRDrawableObject.h \
GRObjectControlPoint.h \
GRPathObject.h \
GRPathEditor.h \
GRCircle.h \
GRCircleEditor.h \
GRImage.h \
GRImageEditor.h

#
# Objective-C Class files
#
Graphos_OBJC_FILES = \
Graphos.m \
GRBezierControlPoint.m \
GRBezierPathEditor.m \
GRDocument.m \
GRDocView.m \
GRFunctions.m \
GRPropsEditor.m \
GRText.m \
GRTextEditor.m \
GRTextEditorView.m \
GRTools.m \
GRBox.m \
GRBoxEditor.m \
GRBezierPath.m \
GRObjectEditor.m \
GRDrawableObject.m \
GRObjectControlPoint.m \
GRPathObject.m \
GRPathEditor.m \
GRCircle.m \
GRCircleEditor.m \
GRImage.m \
GRImageEditor.m

#
# Other sources
#
Graphos_OBJC_FILES += \
main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
