#
#  BouncyClock InnerSpace module
#

BouncyClock_PRINCIPAL_CLASS = BouncyClockView

include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = BouncyClock
BUNDLE_EXTENSION = .InnerSpace

BouncyClock_OBJC_FILES = BouncyClockView.m
BouncyClock_PRINCIPAL_CLASS = BouncyClockView
BouncyClock_STANDARD_INSTALL = no

-include GNUmakefile.preamble

-include ../GNUmakefile.local

-include $(GNUSTEP_MAKEFILES)/bundle.make

-include GNUmakefile.postamble
