Neko_PRINCIPAL_CLASS = NekoView

include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = Neko
BUNDLE_EXTENSION = .InnerSpace

Neko_OBJC_FILES = NekoView.m
Neko_PRINCIPAL_CLASS = NekoView
Neko_STANDARD_INSTALL = no

-include GNUmakefile.preamble

-include ../GNUmakefile.local

-include $(GNUSTEP_MAKEFILES)/bundle.make

-include GNUmakefile.postamble
