SystemStats_PRINCIPAL_CLASS = SystemStatsView

include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = SystemStats
BUNDLE_EXTENSION = .InnerSpace

SystemStats_OBJC_FILES = SystemStatsView.m
SystemStats_PRINCIPAL_CLASS = SystemStatsView
SystemStats_STANDARD_INSTALL = no

-include GNUmakefile.preamble

-include ../GNUmakefile.local

-include $(GNUSTEP_MAKEFILES)/bundle.make

-include GNUmakefile.postamble
