include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = Switcher

OBJCFLAGS += -Wall

Switcher_OBJC_FILES = Switcher.m 

Switcher_PRINCIPAL_CLASS = Switcher

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/bundle.make

-include GNUmakefile.postamble

