include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME = LapisPuzzle
VERSION = 0.9.2
APP_NAME = LapisPuzzle
#agendum-client

LapisPuzzle_MAIN_MODEL_FILE = LapisPuzzle.gorm

LapisPuzzle_OBJC_FILES = main.m \
						 LPController.m \
						 LapisPuzzleView.m


LapisPuzzle_APPLICATION_ICON = LapisPuzzle.tiff

LapisPuzzle_RESOURCE_FILES = LapisPuzzle.gorm LapisPuzzle.tiff LapisPuzzleInfo.plist

include $(GNUSTEP_MAKEFILES)/application.make

