include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME = LapisPuzzle
VERSION = 1.2
APP_NAME = LapisPuzzle

LapisPuzzle_MAIN_MODEL_FILE = LapisPuzzle.gorm

LapisPuzzle_HEADER_FILES = LPController.h \
                           LapisPuzzle.h \
                           LapisPuzzleView.h

LapisPuzzle_OBJC_FILES = main.m \
			 LPController.m \
			 LapisPuzzleView.m


LapisPuzzle_APPLICATION_ICON = LapisPuzzle.tiff

LapisPuzzle_RESOURCE_FILES = LapisPuzzle.gorm LapisPuzzle.tiff LapisPuzzleInfo.plist

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/application.make

