#
# SignalHead InnerSpace module
#

SignalHead_PRINCIPAL_CLASS = SignalHeadView

include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = SignalHead
BUNDLE_EXTENSION = .InnerSpace

SignalHead_OBJC_FILES = SignalHeadView.m
SignalHead_PRINCIPAL_CLASS = SignalHeadView
SignalHead_STANDARD_INSTALL = no

-include GNUmakefile.preamble

-include ../GNUmakefile.local

-include $(GNUSTEP_MAKEFILES)/bundle.make

-include GNUmakefile.postamble
