include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME = Ladder
VERSION = 0.0.1
APP_NAME = Ladder

Ladder_MAIN_MODEL_FILE = Ladder.gorm

Ladder_OBJC_FILES = main.m \
					GameVS.m \
					AppController.m \
					Go.m \
					StoneUI.m \
					Board.m \
					Player.m \
					GNUGoPlayer.m \
					PlayerController.m \
					PlayerCell.m \
					PlayerInfo.m \
					Clock.m \
					ClockController.m \
					ImageBox.m \
					GoDocument.m


Ladder_APPLICATION_ICON = Ladder.tiff

Ladder_RESOURCE_FILES = Ladder.gorm Clock.gorm GoDocument.gorm Ladder.tiff LadderInfo.plist wood.jpg man_icon.png machine_icon.png COPYING.GPL

include $(GNUSTEP_MAKEFILES)/application.make

