include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME = Ladder
VERSION = 0.0.1
APP_NAME = Ladder

Ladder_MAIN_MODEL_FILE = Ladder.gorm

Ladder_OBJC_FILES = main.m \
					AppController.m \
					Go.m \
					StoneUI.m \
					Board.m


Ladder_APPLICATION_ICON = Ladder.tiff

Ladder_RESOURCE_FILES = Ladder.gorm Ladder.tiff Ladder.plist wood.jpg

include $(GNUSTEP_MAKEFILES)/application.make

