.TH TIMEMON 1 "January 24, 2005"
.SH NAME
TimeMon \- CPU time usage monitor
.SH SYNOPSIS
.B TimeMon
.SH DESCRIPTION
This manual page documents briefly the
.B TimeMon
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
\fBTimeMon\fP gives a graphical representation of where the CPU cycles
are going. It's coarse, but better than nothing.
.SH SEE ALSO
.BR GNUstep (7).
.br
.SH AUTHOR
This manual page was written by G\[:u]rkan Myczko <gurkan@phys.ethz.ch>,
for the Debian project (but may be used by others).
