/* Generated by the NeXT Project Builder 
   NOTE: Do NOT change this file -- Project Builder maintains it.
*/

#import <AppKit/AppKit.h>

int main(int argc, const char *argv[]) 
{
  /*
    [NSApplication sharedApplication];
    if ([NSBundle loadNibNamed:@"TimeMon" owner:NSApp])
	    [NSApp run];
	    
    [NSApp release];
    return 0;
  */
  return NSApplicationMain(argc, argv);
}
