include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME = TestTimeUI

APP_NAME = TestTimeUI

FRAMEWORKS = TimeUI

TestTimeUI_OBJC_FILES = main.m AppController.m

TestTimeUI_MAIN_MODEL_FILE = TestTimeUI.gorm

TestTimeUI_RESOURCE_FILES = TestTimeUI.gorm

include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/application.make

