include $(GNUSTEP_MAKEFILES)/common.make
SUBPROJECTS = \
	VCFViewer          \
	adgnumailconverter \
	adserver           \
	adtool             \
	LDAPAddressBook
-include GNUMakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUMakefile.postamble