include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME = AClock
VERSION = 0.4.0
APP_NAME = AClock
AClock_MAIN_MODEL_FILE=AClock.gorm
AClock_APPLICATION_ICON=AClock.tiff

AClock_OBJC_FILES = main.m Clock.m AppController.m
AClock_RESOURCE_FILES = AClock.gorm AClock.tiff \
						cuckoo0.png \
						cuckoo1.png \
						cuckoo2.png \
						cuckoo3.png \
						cuckoo4.png \
						cuckoo5.png \
						cuckoo6.png \
						cuckoo7.png \
						cuckoo8.png \
						cuckoo9.png \
						cuckoo10.png \
						cuckoo11.png \
						cuckoo12.png \
						cuckoo13.png \
						cuckoo14.png \
						cuckoo15.png \
						cuckoo16.png \
						cuckoo17.png \
						cuckoo18.png \
						cuckoo19.png \
						cuckoo.wav \
						ring.wav

include $(GNUSTEP_MAKEFILES)/application.make
