include $(GNUSTEP_MAKEFILES)/common.make

FRAMEWORK_NAME = TalkSoupBundles

TalkSoupBundles_LANGUAGES = English

TalkSoupBundles_LOCALIZED_RESOURCE_FILES = Localizable.strings

TalkSoupBundles_HEADER_FILES = TalkSoup.h TalkSoupProtocols.h TalkSoupMisc.h Encodings.h
TalkSoupBundles_OBJC_FILES = TalkSoup.m Functions.m Dummy.m Encodings.m
TalkSoupBundles_CURRENT_VERSION_NAME=0.990
TalkSoupBundles_DEPLOY_WITH_CURRENT_VERSION=yes

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/framework.make
-include GNUmakefile.postamble
	
