include $(GNUSTEP_MAKEFILES)/common.make

ifeq ($(USE_APPKIT),)
USE_APPKIT=yes
endif

SUBPROJECTS = IRCSwarm

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
