include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = exec_helper dns_helper
TOOL_INSTALL_DIR = Tools

exec_helper_OBJC_FILES = exec_helper.m
dns_helper_OBJC_FILES = dns_helper.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
