#
# GNUmakefile - Generated by ProjectCenter
#

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 1.1.99
PACKAGE_NAME = MPDCon
APP_NAME = MPDCon
MPDCon_APPLICATION_ICON = MPDCon.tiff
GNUSTEP_INSTALLATION_DIR = $(HOME)


#
# Resource files
#
MPDCon_RESOURCE_FILES = \
Resources/Player.gorm \
Resources/Preferences.gorm \
Resources/PlaylistViewer.gorm \
Resources/Collection.gorm \
Resources/PlaylistsManager.gorm \
Resources/StatisticsViewer.gorm \
Resources/CrossfadeView.gorm\
Resources/Play.tiff \
Resources/Pause.tiff \
Resources/Next.tiff \
Resources/Prev.tiff \
Resources/Stop.tiff \
Resources/GNUstep.tiff \
Resources/Repeat.tiff \
Resources/Shuffle.tiff \
Resources/Playlist.tiff \
Resources/Crossfade.tiff \
Resources/MPDCon.tiff \
Resources/MoveSong.tiff \
Resources/Current.tiff\
Resources/Info-gnustep.plist\
Resources/Install \
Resources/COPYING \
Resources/TODO.txt

#
# Header files
#
MPDCon_HEADER_FILES = \
AppController.h \
PreferencesController.h \
PlayView.h \
libmpdclient.h \
PlaylistController.h \
MPDController.h \
PlaylistItem.h \
CollectionController.h \
PlaylistsManagerController.h \
StatisticsController.h \
StatisticsItem.h \
CrossfadeController.h \
OwnTableView.h \
Strings.h \
BoldCell.h \
BoldFormatter.h \
NormalFormatter.h

#
# Class files
#
MPDCon_OBJC_FILES = \
AppController.m \
PreferencesController.m \
PlayView.m \
PlaylistController.m \
MPDController.m \
PlaylistItem.m \
CollectionController.m \
PlaylistsManagerController.m \
StatisticsController.m \
StatisticsItem.m \
CrossfadeController.m \
OwnTableView.m \
BoldCell.m \
BoldFormatter.m \
NormalFormatter.m

#
# C files
#
MPDCon_C_FILES = \
libmpdclient.c 

MPDCon_OBJC_FILES += \
main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
