#
#  Flying Toasters InnerSpace module
#

FlyingToasters_PRINCIPAL_CLASS = FlyingToastersView

include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = FlyingToasters
BUNDLE_EXTENSION = .InnerSpace

FlyingToasters_OBJC_FILES = FlyingToastersView.m
FlyingToasters_PRINCIPAL_CLASS = FlyingToastersView
FlyingToasters_STANDARD_INSTALL = no

-include GNUmakefile.preamble

-include ../GNUmakefile.local

-include $(GNUSTEP_MAKEFILES)/bundle.make

-include GNUmakefile.postamble
