#
# Boink InnerSpace module
#

Boink_PRINCIPAL_CLASS = BoinkView

include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = Boink
BUNDLE_EXTENSION = .InnerSpace

Boink_OBJC_FILES = BoinkView.m
Boink_PRINCIPAL_CLASS = BoinkView
Boink_STANDARD_INSTALL = no

-include GNUmakefile.preamble

-include ../GNUmakefile.local

-include $(GNUSTEP_MAKEFILES)/bundle.make

-include GNUmakefile.postamble
