#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = Vespucci
APP_NAME = Vespucci
Vespucci_APPLICATION_ICON = vespucci_pastel_64.tif


#
# Libraries
#
Vespucci_LIBRARIES_DEPEND_UPON += -lSimpleWebKit 

#
# Resource files
#
Vespucci_RESOURCE_FILES = \
Resources/MainMenu.gorm \
Resources/VEDocument.gorm \
Resources/vespucci_pastel_64.tif \
Resources/back_arrow.tif \
Resources/forward_arrow.tif \
Resources/Vespucci_FileIcon_html.tiff 


#
# Header files
#
Vespucci_HEADER_FILES = \
VEWinController.h \
VEAppController.h \
VEDocument.h \
VEDocumentController.h \
VEFunctions.h \
VEMenuItem.h

#
# Class files
#
Vespucci_OBJC_FILES = \
VEWinController.m \
VEAppController.m \
VEDocument.m \
VEDocumentController.m \
VEFunctions.m \
VEMenuItem.m

#
# Other sources
#
Vespucci_OBJC_FILES += \
main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
