include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=adgnumailconverter

adgnumailconverter_OBJC_FILES=main.m
adgnumailconverter_LDFLAGS += -lAddresses

-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
