#
#  DictionaryWords InnerSpace module
#

DictionaryWords_PRINCIPAL_CLASS = DictionaryWordsView

include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = DictionaryWords
BUNDLE_EXTENSION = .InnerSpace

DictionaryWords_OBJC_FILES = DictionaryWordsView.m
DictionaryWords_PRINCIPAL_CLASS = DictionaryWordsView
DictionaryWords_STANDARD_INSTALL = no

-include GNUmakefile.preamble

-include ../GNUmakefile.local

-include $(GNUSTEP_MAKEFILES)/bundle.make

-include GNUmakefile.postamble
