#
# Generated by the NeXT Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = loginpanel

PROJECTVERSION = 2.6
PROJECT_TYPE = Application
LANGUAGE = English

NEXTSTEP_APPICON = loginicon.tiff
ICONSECTIONS =	-sectcreate __ICON app loginicon.tiff

LOCAL_RESOURCES = InfoPanel.nib NEXTSTEP_loginpanel.nib\
                  WINDOWS_loginpanel.nib

GLOBAL_RESOURCES = gnustep.tiff loginicon.tiff loginPanel.tiff\
                   loginPanelBlank.tiff power.tiff restart.tiff

CLASSES = LoginImageView.m LoginPanelController.m LoginWindow.m\
          LoginTheme.m

HFILES = LoginImageView.h LoginPanelController.h LoginWindow.h\
         LoginTheme.h

MFILES = loginpanel_main.m

OTHERSRCS = Makefile.preamble Makefile Makefile.postamble m.template\
            h.template


MAKEFILEDIR = $(NEXT_ROOT)/NextDeveloper/Makefiles/pb_makefiles
CODE_GEN_STYLE = DYNAMIC
MAKEFILE = app.make
NEXTSTEP_INSTALLDIR = $(HOME)/Apps
WINDOWS_INSTALLDIR = /MyApps
LIBS = 
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)


NEXTSTEP_PB_CFLAGS = -g -DDEBUG
FRAMEWORKS = -framework AppKit -framework Foundation


include $(MAKEFILEDIR)/platform.make

-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
