# Preamble Definitions
GRR_TOP_DIR := $(patsubst %/,%,$(abspath $(dir $(lastword $(MAKEFILE_LIST)))))
GRR_RSSKIT_DIR := $(GRR_TOP_DIR)/../../libs/RSSKit

ADDITIONAL_INCLUDE_DIRS += -I$(GRR_RSSKIT_DIR)/ -F$(GRR_RSSKIT_DIR)
ADDITIONAL_LIB_DIRS += -L$(GRR_RSSKIT_DIR)/RSSKit.framework/
ADDITIONAL_GUI_LIBS += -lRSSKit
